### ISSUE TITLE
ESMTP args truncated in RCPT TO stage

### ISSUE THREAD

**Issue by hxdmp** [d--j/go-milter#15]
I'm using this library to build a Milter server connected to a Postfix instance. Doing that, I noticed that the `esmtpArgs` parameter at the `RCPT TO` stage is truncated. Precisely, only one substring after the first `\0` byte is respected, althought there might be multiple ones. One example where this can happen is when the client requests a DSN (https://www.rfc-editor.org/rfc/rfc3461.html#section-4.1). But other cases are possible, see: https://www.rfc-editor.org/rfc/rfc3461.html#section-10.1

Let me explain this whole thing with an example to make it clearer.

1. Spin up a basic Milter server with the following `RCPT TO` hook:

```go
func (m *myMilter) RcptTo(rcptTo, esmtpArgs string, _ *milter.Modifier) (*milter.Response, error) {
    fmt.Printf("RCPT TO: %q; esmtpArgs: %q\n", rcptTo, esmtpArgs)
    return milter.RespContinue, nil
}
```

2. Submit the following (valid) `RCPT TO` command to your mail server:

```
RCPT TO: <test@example.com> NOTIFY=SUCCESS ORCPT=rfc822;test@anotherexample.com
```

3. The following is received by the Milter and printed to the console:

```
RCPT TO: "test@example.com"; esmtpArgs: "NOTIFY=SUCCESS"
```

4. Inspecting the raw bytes, one can see that there was actually more data:

```
"test@example.com\x00NOTIFY=SUCCESS\x00ORCPT=rfc822;test@anotherexample.com\x00"
```

## Conclusion

This behavior is probably caused by the following code:
https://github.com/d--j/go-milter/blob/30d4d62396d57db43116e28f8bb5c5b61ecf2478/session.go#L224C1-L224C1

Maybe it's already sufficient to replace all occurrences of `0x00` after the email address with a space and pass that to the Milter interface implementation. As this is not a real C string, there should be no harm in doing so (we don't need a zero-terminator).

I'm waiting for your feedback before starting to implement it.

**Comment by d--j** [comment]
Hi @hxdmp 

thanks for poiting that out. I was under the impression that Postfix/Sendmail passes in all values as space seperated second string.

Your proposed solution sounds good to me. One can use [`DecodeCStrings`](https://github.com/d--j/go-milter/blob/30d4d62396d57db43116e28f8bb5c5b61ecf2478/internal/wire/cstrings.go#L13) to get a string slice and join it with space.

The [MAIL ESMTP](https://github.com/d--j/go-milter/blob/30d4d62396d57db43116e28f8bb5c5b61ecf2478/session.go#L214) args need the same handling.

**Comment by hxdmp** [comment]
Thanks for that very fast response! I'll implement that and open a pull request.

**Comment by hxdmp** [comment]
I created #16 to fix this for both instances. Due to the implementation of `DecodeCStrings`, the trailing zero-byte in the input data is omitted - in other words: There is no trailing space.
